# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: CSS Experiments
lang: en_GB
email: clarebee@protonmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Experiments in CSS, inspired by Lea Verou and CSS Tricks.
baseurl: /css-experiments # the subpath of your site, e.g. /blog
twitter_username: jekyllrb
github_username:  jekyll
author: clarebee
twitter:
  username: clarie_bee
  card: summary
logo: /assets/img/apple-touch-icon.png

# Build settings
markdown: kramdown
theme: minima
minima:
  skin: customised
show_excerpts: true
defaults:
  -
    scope:
      path: ""
    values:
      image: /assets/img/apple-touch-icon.png
      excerpt_separator: <!--more-->
plugins:
  - jekyll-feed
  - jekyll-archives
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji
  - jekyll-relative-links
sass:
  style: compact # possible values: nested expanded compact compressed
published: true
future: true
assets:
  sources:
    - assets/img
    - assets/css
paginate: 5

jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

google_analytics: UA-NNNNNNNN-N

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
